### ISSUE TITLE
Heroku deploy build success but can't get POST responses

### ISSUE THREAD

**Issue by luisampuerovalenzuela** [ashwamegh/link-preview-generator-server#1]
Hello friend,

How are you? I hope you doing well.

I was able to build this project on heroku adding a Profile with 'web: node ./bin/www' but can't get POST responses there. It even show me this with a browser GET:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/96737011/170532443-29168eaf-7c93-4111-bc00-b6aa08a0c88d.png">

On the other hand, when I ran the project on my local environment it works perfect. Using postman I can get the correct responses for POST.

Can you please help me to figure out how can I run this repo on heroku and get the correct responses on POST request?

Regards and thanks in advance.
Luis

**Comment by ashwamegh** [comment]
Hey @luisampuerovalenzuela Hope you resolved your issue, Marking it closed. Feel free to ping if you are facing the issue.
